version: '3.1'

services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8000:8080'